import type { Card } from './types.js'

export const TAROT_DECK: readonly Card[] = [
  // Major Arcana (22 cards)
  { id: 'the-fool', name: 'The Fool', suit: 'Major Arcana' },
  { id: 'the-magician', name: 'The Magician', suit: 'Major Arcana' },
  { id: 'the-high-priestess', name: 'The High Priestess', suit: 'Major Arcana' },
  { id: 'the-empress', name: 'The Empress', suit: 'Major Arcana' },
  { id: 'the-emperor', name: 'The Emperor', suit: 'Major Arcana' },
  { id: 'the-hierophant', name: 'The Hierophant', suit: 'Major Arcana' },
  { id: 'the-lovers', name: 'The Lovers', suit: 'Major Arcana' },
  { id: 'the-chariot', name: 'The Chariot', suit: 'Major Arcana' },
  { id: 'strength', name: 'Strength', suit: 'Major Arcana' },
  { id: 'the-hermit', name: 'The Hermit', suit: 'Major Arcana' },
  { id: 'wheel-of-fortune', name: 'Wheel of Fortune', suit: 'Major Arcana' },
  { id: 'justice', name: 'Justice', suit: 'Major Arcana' },
  { id: 'the-hanged-man', name: 'The Hanged Man', suit: 'Major Arcana' },
  { id: 'death', name: 'Death', suit: 'Major Arcana' },
  { id: 'temperance', name: 'Temperance', suit: 'Major Arcana' },
  { id: 'the-devil', name: 'The Devil', suit: 'Major Arcana' },
  { id: 'the-tower', name: 'The Tower', suit: 'Major Arcana' },
  { id: 'the-star', name: 'The Star', suit: 'Major Arcana' },
  { id: 'the-moon', name: 'The Moon', suit: 'Major Arcana' },
  { id: 'the-sun', name: 'The Sun', suit: 'Major Arcana' },
  { id: 'judgement', name: 'Judgement', suit: 'Major Arcana' },
  { id: 'the-world', name: 'The World', suit: 'Major Arcana' },

  // Wands (14 cards)
  { id: 'ace-of-wands', name: 'Ace of Wands', suit: 'Wands' },
  { id: 'two-of-wands', name: 'Two of Wands', suit: 'Wands' },
  { id: 'three-of-wands', name: 'Three of Wands', suit: 'Wands' },
  { id: 'four-of-wands', name: 'Four of Wands', suit: 'Wands' },
  { id: 'five-of-wands', name: 'Five of Wands', suit: 'Wands' },
  { id: 'six-of-wands', name: 'Six of Wands', suit: 'Wands' },
  { id: 'seven-of-wands', name: 'Seven of Wands', suit: 'Wands' },
  { id: 'eight-of-wands', name: 'Eight of Wands', suit: 'Wands' },
  { id: 'nine-of-wands', name: 'Nine of Wands', suit: 'Wands' },
  { id: 'ten-of-wands', name: 'Ten of Wands', suit: 'Wands' },
  { id: 'page-of-wands', name: 'Page of Wands', suit: 'Wands' },
  { id: 'knight-of-wands', name: 'Knight of Wands', suit: 'Wands' },
  { id: 'queen-of-wands', name: 'Queen of Wands', suit: 'Wands' },
  { id: 'king-of-wands', name: 'King of Wands', suit: 'Wands' },

  // Cups (14 cards)
  { id: 'ace-of-cups', name: 'Ace of Cups', suit: 'Cups' },
  { id: 'two-of-cups', name: 'Two of Cups', suit: 'Cups' },
  { id: 'three-of-cups', name: 'Three of Cups', suit: 'Cups' },
  { id: 'four-of-cups', name: 'Four of Cups', suit: 'Cups' },
  { id: 'five-of-cups', name: 'Five of Cups', suit: 'Cups' },
  { id: 'six-of-cups', name: 'Six of Cups', suit: 'Cups' },
  { id: 'seven-of-cups', name: 'Seven of Cups', suit: 'Cups' },
  { id: 'eight-of-cups', name: 'Eight of Cups', suit: 'Cups' },
  { id: 'nine-of-cups', name: 'Nine of Cups', suit: 'Cups' },
  { id: 'ten-of-cups', name: 'Ten of Cups', suit: 'Cups' },
  { id: 'page-of-cups', name: 'Page of Cups', suit: 'Cups' },
  { id: 'knight-of-cups', name: 'Knight of Cups', suit: 'Cups' },
  { id: 'queen-of-cups', name: 'Queen of Cups', suit: 'Cups' },
  { id: 'king-of-cups', name: 'King of Cups', suit: 'Cups' },

  // Swords (14 cards)
  { id: 'ace-of-swords', name: 'Ace of Swords', suit: 'Swords' },
  { id: 'two-of-swords', name: 'Two of Swords', suit: 'Swords' },
  { id: 'three-of-swords', name: 'Three of Swords', suit: 'Swords' },
  { id: 'four-of-swords', name: 'Four of Swords', suit: 'Swords' },
  { id: 'five-of-swords', name: 'Five of Swords', suit: 'Swords' },
  { id: 'six-of-swords', name: 'Six of Swords', suit: 'Swords' },
  { id: 'seven-of-swords', name: 'Seven of Swords', suit: 'Swords' },
  { id: 'eight-of-swords', name: 'Eight of Swords', suit: 'Swords' },
  { id: 'nine-of-swords', name: 'Nine of Swords', suit: 'Swords' },
  { id: 'ten-of-swords', name: 'Ten of Swords', suit: 'Swords' },
  { id: 'page-of-swords', name: 'Page of Swords', suit: 'Swords' },
  { id: 'knight-of-swords', name: 'Knight of Swords', suit: 'Swords' },
  { id: 'queen-of-swords', name: 'Queen of Swords', suit: 'Swords' },
  { id: 'king-of-swords', name: 'King of Swords', suit: 'Swords' },

  // Pentacles (14 cards)
  { id: 'ace-of-pentacles', name: 'Ace of Pentacles', suit: 'Pentacles' },
  { id: 'two-of-pentacles', name: 'Two of Pentacles', suit: 'Pentacles' },
  { id: 'three-of-pentacles', name: 'Three of Pentacles', suit: 'Pentacles' },
  { id: 'four-of-pentacles', name: 'Four of Pentacles', suit: 'Pentacles' },
  { id: 'five-of-pentacles', name: 'Five of Pentacles', suit: 'Pentacles' },
  { id: 'six-of-pentacles', name: 'Six of Pentacles', suit: 'Pentacles' },
  { id: 'seven-of-pentacles', name: 'Seven of Pentacles', suit: 'Pentacles' },
  { id: 'eight-of-pentacles', name: 'Eight of Pentacles', suit: 'Pentacles' },
  { id: 'nine-of-pentacles', name: 'Nine of Pentacles', suit: 'Pentacles' },
  { id: 'ten-of-pentacles', name: 'Ten of Pentacles', suit: 'Pentacles' },
  { id: 'page-of-pentacles', name: 'Page of Pentacles', suit: 'Pentacles' },
  { id: 'knight-of-pentacles', name: 'Knight of Pentacles', suit: 'Pentacles' },
  { id: 'queen-of-pentacles', name: 'Queen of Pentacles', suit: 'Pentacles' },
  { id: 'king-of-pentacles', name: 'King of Pentacles', suit: 'Pentacles' },
] as const
